name: Update Daily News

on:
  schedule:
    # Run at 10:00 AM UTC+8 (02:00 UTC) every day
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update_news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
      
      - name: Fetch latest news
        run: |
          python .github/scripts/fetch_news.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add news.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update news.json for $(date +'%Y-%m-%d')"
          git push